### ISSUE TITLE
tissue does not work with pep8 1.3.1

### ISSUE THREAD

**Issue by bcroq** [wolph/tissue#7]
<pre>File ".../lib/python2.7/site-packages/tissue-0.7-py2.7.egg/tissue.py", lin
    pep8.input_dir(path, runner=seen_runner)
AttributeError: 'module' object has no attribute 'input_dir'
</pre>

**Comment by graffic** [comment]
It sems that the `input_dir` method has been moved to the `StyleGuide` class

**Comment by domenkozar** [comment]
+1

**Comment by jkoelker** [comment]
Sorry, been slammed recently. This is on my todo list, but if anyone has a PR I'd be more than happy to merge it in since I probably won't get a chance to circle back to this for a while.

**Comment by brodul** [comment]
The temp fix is to pinpoint pep8 to `pep8 = 1.2`.

**Comment by jkoelker** [comment]
@renemilk's commit should fix the issue.  On a side note if anyone wants to take ownership of this package I'd be willing to transfer pypi ownership to them.

**Comment by renefritze** [comment]
I'd be willing to take ownership of the package @jkoelker. My username over on pypi is koshi

**Comment by jkoelker** [comment]
Thanks @renemilk I've added you as an owner, you're free to remove my access so you should choose ;). Thanks!
